name: Node.js CI

on:
  - push
  - pull_request

jobs:
  testing:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: make install
    - name: Run linter
      run: make lint
